networks:
  web:
    external: true
  internal:
    external: true
  paperless-ngx:
    driver: bridge

services:
  paperless-ngx-redis:
    image: docker.io/library/redis:8
    container_name: paperless-ngx-redis
    restart: unless-stopped
    networks:
      - paperless-ngx
    volumes:
      - paperlessredisdata:/data
  paperless-ngx:
    extends:
      file: ../common.yml
      service: app
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-ngx
    depends_on:
      - paperless-ngx-redis
    networks:
      - paperless-ngx
      - web
    volumes:
      - $MEDIADIR/paperless/data:/usr/src/paperless/data
      - $MEDIADIR/paperless/media:/usr/src/paperless/media
      - $MEDIADIR/paperless/export:/usr/src/paperless/export
      - $MEDIADIR/paperless/consume:/usr/src/paperless/consume
    env_file:
      - paperless-ngx.env
    environment:
      PAPERLESS_REDIS: redis://paperless-ngx-redis:6379
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paperlessngx-rtr.entrypoints=websecure"
      - "traefik.http.routers.paperlessngx-rtr.rule=Host(`paperless.$DOMAINNAME_1`)"
      - "traefik.http.routers.paperlessngx-rtr.service=paperlessngx-svc"
      - "traefik.http.services.paperlessngx-svc.loadbalancer.server.port=8000"

volumes:
  paperlessredisdata:
