networks:
  internal:
    external: true
  socket_proxy:
    external: true

services:
  dozzle:
    extends:
      file: ../common.yml
      service: core
    container_name: dozzle
    image: amir20/dozzle:latest
    networks:
      internal: {}
      socket_proxy: {}
    environment:
      - DOZZLE_REMOTE_HOST=tcp://socket-proxy:2375
    volumes:
      - dozzle_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle-rtr.entrypoints=internalsecure"
      - "traefik.http.routers.dozzle-rtr.rule=Host(`dozzle.$DOMAINNAME_1`) || Host(`dozzle.${DOCKER_HOST_NAME}.$DOMAINNAME_1`)"
      - "traefik.http.routers.dozzle-rtr.service=dozzle-svc"
      - "traefik.http.services.dozzle-svc.loadbalancer.server.port=8080"
volumes:
  dozzle_data: