networks:
  web:
    external: true
  internal:
    external: true

services:
  beets-flask:
    extends:
      file: ../common.yml
      service: app
    image: pspitzner/beets-flask:stable
    container_name: beets-flask
    networks:
      - internal
      - arr
    volumes:
      - $DATADIR/appdata/beets-flask/beets/:/config/beets/
      - $DATADIR/appdata/beets-flask/beets-flask/:/config/beets-flask/
      - $DATADIR/secrets/beets-secrets.yaml:/config/beets/secrets.yaml
      - $MEDIADIR/music:/music/
      - $MEDIADIR/ingest/music/:/downloads
      # configs
      - ./config/requirements.txt:/config/requirements.txt:ro
      - ./config/startup.sh:/config/startup.sh:ro
      - ./config/beets-flask-config.yaml:/config/beets-flask/config.yaml:ro
      - ./config/beets-config.yaml:/config/beets/config.yaml:ro

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.beetsflask-rtr.entrypoints=internalsecure"
      - "traefik.http.routers.beetsflask-rtr.rule=Host(`beetsflask.${DOCKER_HOST_NAME}.i.$DOMAINNAME_1`) || Host(`beetsflask.$DOMAINNAME_1`)"
      - "traefik.http.routers.beetsflask-rtr.service=beetsflask-svc"
      - "traefik.http.services.beetsflask-svc.loadbalancer.server.port=5001"
      - "traefik.docker.network=internal"
      - "logging=alloy"
      - "logging_jobname=containerlogs"
