services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    networks:
      - caddy-net
      - socket_proxy
    environment:
      - DOCKER_HOST=tcp://socket-proxy:2375
      - CADDY_INGRESS_NETWORKS=caddy-net
    volumes:
      - $DOCKERDIR/appdata/caddy:/data
    restart: unless-stopped
    labels:
      caddy.email: jamienibtong@gmail.com
      caddy.auto_https: "ignore_loaded_certs"
