services:
  rcon-web:
    image: itzg/rcon
    container_name: rcon-web
    networks:
      - internal
      - minecraft
    env_file:
      - $CONFIGDIR/.env
      - $CONFIGDIR/minecraft.env
    restart: unless-stopped
    security_opt:
      - no-new-privileges:false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rcon-web-rtr.entrypoints=internalsecure"
      - "traefik.http.routers.rcon-web-rtr.rule=Host(`rcon-web.${DOCKER_HOST_NAME}.i.$DOMAINNAME_1`)"
      - "traefik.http.routers.rcon-web-rtr.service=rcon-web-svc"
      - "traefik.http.services.rcon-web-svc.loadbalancer.server.port=4326"
      - "traefik.http.routers.rcon-web-wss-rtr.entrypoints=internalsecure"
      - "traefik.http.routers.rcon-web-wss-rtr.rule=Host(`rcon-web.${DOCKER_HOST_NAME}.i.$DOMAINNAME_1`) && Header(`Connection`, `Upgrade`) && Header(`Upgrade`, `websocket`)"
      - "traefik.http.routers.rcon-web-wss-rtr.service=rcon-web-wss-svc"
      - "traefik.http.services.rcon-web-wss-svc.loadbalancer.server.port=4327"
      - "traefik.docker.network=internal"
      - "logging=alloy"
      - "logging_jobname=containerlogs"

  smp:
    image: itzg/minecraft-server:java21-alpine
    tty: true
    container_name: mc-smp
    stdin_open: true
    networks:
      - minecraft
    env_file:
      - $CONFIGDIR/.env
      - $CONFIGDIR/minecraft.env
    ports:
      - "25565:25565"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:false
    volumes:
      # attach the relative directory 'data' to tsdfhe container's /data path
      - $DATADIR/data/minecraft/instances/smp:/data
    labels:
      logging: alloy
      logging_jobname: containerlogs

networks:
  minecraft:
    name: minecraft
    driver: bridge
