networks:
  synapsenet:
    external:
      name: synapsenet

services:
  mautrix-whatsapp:
    container_name: mautrix-whatsapp
    image: dock.mau.dev/mautrix/whatsapp:latest
    restart: unless-stopped
    volumes:
    - $DATADIR/appdata/mautrix-whatsapp/data:/data
    networks:
    - synapsenet
