networks:
  amdl:
    driver: bridge

services:
  apple-music-downloader: 
    extends:
      file: ../common.yml
      service: app
    image: ghcr.io/zhaarey/apple-music-downloader
    container_name: apple-music-downloader
    networks:
      amdl: {}
    volumes:
      - $MEDIADIR/music:/music/
      - $MEDIADIR/ingest/music/:/downloads
  apple-music-wrapper: 
    extends:
      file: ../common.yml
      service: app
    image: ghcr.io/worldobservationlog/wrapper:local
    container_name: apple-music-wrapper
    privileged: true
    networks:
      amdl: {}
    volumes:
      - /home/faith/git/wrapper/rootfs/data:/app/rootfs/data
  apple-music-wrapper-login:
    extends: apple-music-wrapper
    restart: on-failure:3
    profiles:
      - wrapper-login
    entrypoint: ["./wrapper"]
    command: ["-L", "${AM_USERNAME}:${AM_PASSWORD}", "-H", "127.0.0.1"]
