networks:
  internal:
    external: true

services:
  openbao:
    extends:
      file: ../common.yml
      service: core
    image: quay.io/openbao/openbao:2.0
    container_name: openbao
    restart: unless-stopped
    environment:
      BAO_LOCAL_CONFIG: |
        storage "file" {
          path = "/openbao/data"
        }
        listener "tcp" {
          address     = "0.0.0.0:8200"
          tls_disable = "true"
        }
        ui = true
    volumes:
      - $DATADIR/data/bao-data:/openbao/data
    networks:
      internal: {}
    cap_add:
      - IPC_LOCK
    labels:
      - "traefik.enable=true"
      # HTTP Router & TLS Rules
      - "traefik.http.routers.openbao.rule=Host(`openbao.$DOMAINNAME_1`) || Host(`openbao.${DOCKER_HOST_NAME}.i.$DOMAINNAME_1`)"
      - "traefik.http.routers.openbao.entrypoints=internalsecure"
      # Target backend port inside container
      - "traefik.http.services.openbao.loadbalancer.server.port=8200"
      # Recommended OpenBao Security Middlewares
      - "traefik.http.routers.openbao.middlewares=bao-headers"
      - "traefik.http.middlewares.bao-headers.headers.browserXSSFilter=true"
      - "traefik.http.middlewares.bao-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.bao-headers.headers.stsSeconds=31536000"
      - "traefik.docker.network=internal"