########################### NETWORKS
networks:
  t3_proxy:
    name: t3_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24

secrets: 
  cf_dns_api_token:
    file: $DOCKERDIR/secrets/cf_dns_api_token

########################### SERVICES
include:
  - compose/winsucks/traefik.yml
  - compose/winsucks/jellyfin.yml
  - compose/winsucks/arr.yml
  - compose/winsucks/immich.yml
  - compose/winsucks/qbittorrent.yml
  - compose/winsucks/recyclarr.yml
  - compose/winsucks/kavita.yml
  - compose/winsucks/tachidesk.yml
  - compose/winsucks/slskd.yml
  - compose/winsucks/betanin.yml
  - compose/winsucks/gonic.yml
  - compose/winsucks/lms.yml

