networks:
  web:
    name: web
    driver: bridge

secrets:
  cf_dns_api_token:
    file: $DATADIR/secrets/cf_dns_api_token

include:
  - compose/common/socket-proxy.yml
  - compose/beta/alloy.yml
  - compose/beta/traefik.yml
  - compose/beta/minecraft.yml
#   - compose/beta/syncyomi.yml
