########################### NETWORKS
# You may customize the network subnet (192.168.89.0/24) below as you please.
# Docker Compose version 3.5 or higher required to define networks this way.

networks:
  web:
    external: true

include:
   - compose/common/socket-proxy.yml
   - compose/alpha/alloy.yml
   - compose/alpha/caddy.yml
   - compose/alpha/mailserver.yml
   - compose/alpha/syncyomi.yml
   - compose/alpha/forgejo.yml
   #   - compose/alpha/postgres.yml
