networks:
  web:
    name: web
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
  internal:
    name: internal
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24

secrets:
  cf_dns_api_token:
    file: $DATADIR/secrets/cf_dns_api_token

include:
  - compose/common/socket-proxy/compose.yml
  - compose/${DOCKER_HOST_NAME}/alloy/compose.yml
  - compose/${DOCKER_HOST_NAME}/authelia/compose.yml
  - compose/${DOCKER_HOST_NAME}/traefik/compose.yml
  - compose/${DOCKER_HOST_NAME}/minecraft/compose.yml
  - compose/${DOCKER_HOST_NAME}/immich-public-proxy/compose.yml
  - compose/${DOCKER_HOST_NAME}/syncyomi/compose.yml
  - compose/${DOCKER_HOST_NAME}/homepage/compose.yml
