########################### NETWORKS
# You may customize the network subnet (192.168.89.0/24) below as you please.
# Docker Compose version 3.5 or higher required to define networks this way.

networks:
  caddy-net:
    name: caddy-net
    driver: bridge
  mailserver-proxy:
    name: mailserver-proxy
    driver: bridge
    ipam:
      config:
        - subnet: 11.0.0.0/16

include:
   - compose/alpha/mailserver.yml
   - compose/alpha/syncyomi.yml
   #   - compose/alpha/postgres.yml
