########################### NETWORKS
# You may customize the network subnet (192.168.89.0/24) below as you please.
# Docker Compose version 3.5 or higher required to define networks this way.

networks:
  caddy-net:
    name: caddy-net
    driver: bridge

include:
   - compose/common/socket-proxy.yml
   - compose/beta/caddy.yml
   - compose/beta/minecraft.yml
#   - compose/beta/syncyomi.yml
