networks:
  web:
    external: true

secrets:
  cf_dns_api_token:
    file: $DATADIR/secrets/cf_dns_api_token

include:
  - compose/common/socket-proxy.yml
  - compose/alpha/alloy.yml
  - compose/alpha/traefik.yml
  - compose/alpha/mailserver.yml
  - compose/alpha/syncyomi.yml
  - compose/alpha/forgejo.yml
  #   - compose/alpha/postgres.yml
