networks:
  web:
    name: web
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
  internal:
    name: internal
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24

secrets:
  cf_dns_api_token:
    file: $DATADIR/secrets/cf_dns_api_token

include:
  - compose/common/socket-proxy.yml
  - compose/${DOCKER_HOST_NAME}/alloy.yml
  - compose/${DOCKER_HOST_NAME}/traefik.yml
  - compose/${DOCKER_HOST_NAME}/jellyfin.yml
  - compose/${DOCKER_HOST_NAME}/arr.yml
  - compose/${DOCKER_HOST_NAME}/immich.yml
  - compose/${DOCKER_HOST_NAME}/qbittorrent.yml
  - compose/${DOCKER_HOST_NAME}/recyclarr.yml
  - compose/${DOCKER_HOST_NAME}/kavita.yml
  - compose/${DOCKER_HOST_NAME}/tachidesk.yml
  - compose/${DOCKER_HOST_NAME}/slskd.yml
  - compose/${DOCKER_HOST_NAME}/beets-flask.yml
  - compose/${DOCKER_HOST_NAME}/lms.yml
  - compose/${DOCKER_HOST_NAME}/apple-dl.yml
  - compose/${DOCKER_HOST_NAME}/grafana-monitoring.yml
