networks:
  internal:
    external: true

services:
  rdtclient:
    image: rogerfar/rdtclient
    container_name: rdtclient
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    networks:
      - internal
    volumes:
      - $DATADIR/appdata/rdtclient/db:/data/db
      - $MEDIADIR/@media:/data/media
    logging:
       driver: json-file
       options:
          max-size: 10m
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rdtclient-rtr.entrypoints=internalsecure"
      - "traefik.http.routers.rdtclient-rtr.rule=Host(`rdtclient.${DOCKER_HOST_NAME}.i.$DOMAINNAME_1`) || Host(`rdtclient.$DOMAINNAME_1`)"
      - "traefik.http.routers.rdtclient-rtr.service=rdtclient-svc"
      - "traefik.http.services.rdtclient-svc.loadbalancer.server.port=6500"
      - "traefik.docker.network=internal"
    restart: unless-stopped
