configs:
  config.alloy:
    file: $CONFIGDIR/config/grafana-monitoring/alloy/common/config.alloy

services:
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    restart: unless-stopped
    volumes:
      - /var/run:/var/run:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /var/log:/var/log
    configs:
      - source: config.alloy
        target: /etc/alloy/config.alloy
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data --disable-reporting /etc/alloy/config.alloy
    networks:
      web:
      socket_proxy:
    environment:
      - DOCKER_HOST_NAME=${DOCKER_HOST_NAME}
