services:
  navidrome:
    extends:
      file: common.yml
      service: app
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    networks:
      - t3_proxy
    volumes:
      - "$DOCKERDIR/appdata/navidrome:/data"
      - "$DATADIR/music:/music:ro"
      - "/tmp/snapfifo:/tmp/snapfifo"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.navidrome-rtr.entrypoints=websecure"
      - "traefik.http.routers.navidrome-rtr.rule=Host(`navidrome.$DOMAINNAME_1`)"
      - "traefik.http.routers.navidrome-rtr.service=navidrome-svc"
      - "traefik.http.services.navidrome-svc.loadbalancer.server.port=4533"

