services:
  tachidesk:
    extends:
      file: common.yml
      service: app 
    image: ghcr.io/suwayomi/tachidesk:stable
    container_name: tachidesk
    networks:
      - t3_proxy
    volumes: # The order matters! Make sure the downloads is first in the volume list or it will not work!
      - $DATADIR/manga:/home/suwayomi/.local/share/Tachidesk/downloads
      - $DOCKERDIR/appdata/tachidesk:/home/suwayomi/.local/share/Tachidesk
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tachidesk-rtr.entrypoints=websecure"
      - "traefik.http.routers.tachidesk-rtr.rule=Host(`tachidesk.$DOMAINNAME_1`)"
      - "traefik.http.routers.tachidesk-rtr.service=tachidesk-svc"
      - "traefik.http.services.tachidesk-svc.loadbalancer.server.port=4567"

