services:
  alloy:
   image: grafana/alloy:latest
   container_name: alloy
   restart: unless-stopped
   #ports:
   #  - 4317:4317
   #  - 4318:4318
   volumes:
     - $CONFIGDIR/config/grafana-monitoring/alloy/${DOCKER_HOST_NAME}/config.alloy:/etc/alloy/config.alloy
     - /var/run:/var/run:ro
     - /var/lib/docker/:/var/lib/docker:ro
     - /dev/disk/:/dev/disk:ro
     - /var/log:/var/log
   command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
   networks:
     - web
     - socket_proxy
   environment:
     - DOCKER_HOST_NAME=${DOCKER_HOST_NAME}
   labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alloy-rtr.entrypoints=websecure"
      - "traefik.http.routers.alloy-rtr.rule=Host(`alloy.$DOMAINNAME_1`)"
      - "traefik.http.routers.alloy-rtr.service=alloy-svc"
      - "traefik.http.routers.alloy-rtr.tls=true"
      - "traefik.http.services.alloy-svc.loadbalancer.server.port=12345"