configs:
  datasources.yaml:
    file: $CONFIGDIR/config/grafana-monitoring/grafana/datasources.yaml
  prometheus.yml:
    file: $CONFIGDIR/config/grafana-monitoring/prometheus/prometheus.yml
  loki-config.yml:
    file: $CONFIGDIR/config/grafana-monitoring/loki/loki-config.yml

services:
  loki:
    container_name: loki
    image: grafana/loki:main
    networks:
      - web
      - grafana_monitoring
    volumes:
      - $DATADIR/appdata/grafana-monitoring/loki:/etc/loki
    configs:
      - source: loki-config.yml
        target: /etc/loki/loki-config.yml
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.loki-rtr.entrypoints=websecure"
      - "traefik.http.routers.loki-rtr.rule=Host(`loki.$DOMAINNAME_1`)"
      - "traefik.http.routers.loki-rtr.service=loki-svc"
      - "traefik.http.routers.loki-rtr.tls=true"
      - "traefik.http.services.loki-svc.loadbalancer.server.port=3100"
  grafana:
    container_name: grafana
    image: grafana/grafana-oss:main-ubuntu
    user: "0"
    networks:
      - web
      - grafana_monitoring
    volumes:
      - $DATADIR/appdata/grafana-monitoring/grafana/data:/var/lib/grafana
    configs:
      - source: datasources.yaml
        target: /etc/grafana/provisioning/datasources/datasources.yaml
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana-rtr.entrypoints=websecure"
      - "traefik.http.routers.grafana-rtr.rule=Host(`grafana.$DOMAINNAME_1`)"
      - "traefik.http.routers.grafana-rtr.service=grafana-svc"
      - "traefik.http.routers.grafana-rtr.tls=true"
      - "traefik.http.services.grafana-svc.loadbalancer.server.port=3000"
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: unless-stopped
    configs:
      - source: prometheus.yml
        target: /etc/prometheus/prometheus.yml
    networks:
      - web
      - grafana_monitoring
    command: --config.file=/etc/prometheus/prometheus.yml --web.enable-remote-write-receiver
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus-rtr.entrypoints=websecure"
      - "traefik.http.routers.prometheus-rtr.rule=Host(`prometheus.$DOMAINNAME_1`)"
      - "traefik.http.routers.prometheus-rtr.service=prometheus-svc"
      - "traefik.http.routers.prometheus-rtr.tls=true"
      - "traefik.http.services.prometheus-svc.loadbalancer.server.port=9090"
  #promtail:
  #  container_name: promtail
  #  image: grafana/promtail:main
  #  networks:
  #    - grafana_monitoring
  #    - socket_proxy
  #  volumes:
  #    - /var/log:/var/log
  #    - $CONFIGDIR/config/grafana-monitoring/promtail/${DOCKER_HOST_NAME}/promtail-config.yml:/etc/promtail/promtail-config.yml
  #    - $DATADIR/appdata/grafana-monitoring/promtail:/etc/promtail
  #  restart: unless-stopped
  #  command: -config.file=/etc/promtail/promtail-config.yml -client.external-labels=hostname=$${HOSTNAME}
  #  depends_on:
  #    - loki

networks:
  grafana_monitoring:
    name: grafana_monitoring
    driver: bridge
