services:
  # Jellyfin - Media Server 
  jellyfin:
    extends:
        file: common.yml
        service: app
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    networks:
      - web

    #  ipvlan:
    #    ipv4_address: 192.168.1.22
    #  web: {}
    #ports:
    #  - "8096:8096" # HTTP Port
    #  - "1900:1900/udp"
    #  - "8920:8920" # Requires valid certificates.
    
    volumes:
      - $DATADIR/appdata/jellyfin:/config
      - $MEDIADIR/media:/data/media
      - $MEDIADIR/music:/music
      - $MEDIADIR/playlists:/playlists
    #     - /dev/shm:/data/transcode # Offload transcoding to RAM if you have enough RAM

    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128

    #runtime: nvidia
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: all
    #          capabilities: [gpu]
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin-rtr.entrypoints=websecure,internalsecure"
      - "traefik.http.routers.jellyfin-rtr.rule=Host(`jellyfin.$DOMAINNAME_1`)"
      - "traefik.http.routers.jellyfin-rtr.service=jellyfin-svc"
      - "traefik.http.services.jellyfin-svc.loadbalancer.server.port=8096"
      - "logging=alloy"
      - "logging_jobname=containerlogs"

