services:
  recyclarr:
    extends:
      file: common.yml
      service: app
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    networks:
      - arr
    volumes:
      - $DATADIR/appdata/recyclarr/config:/config
