networks:
  internal:
    external: true

services:
  openbao:
    extends:
      file: ../common.yml
      service: core
    image: openbao/openbao:latest
    container_name: openbao
    networks:
      internal: {}
    cap_add:
      - IPC_LOCK
    command: ["server", "-config=/openbao/openbao.hcl"]
    volumes:
      - $DATADIR/data/openbao/data:/openbao/data
      - ./config/openbao.hcl:/openbao/openbao.hcl:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openbao.rule=Host(`openbao.${DOMAINNAME_1}`) || Host(`openbao.${DOCKER_HOST_NAME}.i.${DOMAINNAME_1}`)"
      - "traefik.http.routers.openbao.entrypoints=internalsecure"
      - "traefik.http.routers.openbao.service=openbao-svc"
      - "traefik.http.services.openbao-svc.loadbalancer.server.port=8200"
      - "traefik.docker.network=internal"
