networks:
  web:
    external: true
  internal:
    external: true
  synapsenet:
    name: synapsenet
    driver: bridge

services:
  matrix-synapse:
    container_name: matrix-synapse
    image: matrixdotorg/synapse:latest
    volumes:
      - $DATADIR/appdata/matrix-synapse/data:/data
    networks:
      web: {}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.matrix-synapse-rtr.entrypoints=websecure"
      - "traefik.http.routers.matrix-synapse-rtr.rule=Host(`matrix.$DOMAINNAME_1`)"
      - "traefik.http.routers.matrix-synapse-rtr.service=matrix-synapse-svc"
      - "traefik.http.services.matrix-synapse-svc.loadbalancer.server.port=8008"
      - "logging=alloy"
      - "logging_jobname=containerlogs"
