services:
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    restart: unless-stopped
    #ports:
    #  - 4317:4317
    #  - 4318:4318
    volumes:
      - $CONFIGDIR/config/grafana-monitoring/alloy/common/config.alloy:/etc/alloy/config.alloy
      - /var/run:/var/run:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /var/log:/var/log
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    networks:
      web:
        ipv4_address: 10.10.0.7
      socket_proxy:
    environment:
      - DOCKER_HOST_NAME=${DOCKER_HOST_NAME}
    labels:
      caddy_1: alloy.alpha.jamietong.com
      caddy_1.reverse_proxy: "{{upstreams 12345}}"
