services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    networks:
      socket_proxy:
      web:
        ipv4_address: 10.10.0.2
    environment:
      - DOCKER_HOST=tcp://socket-proxy:2375
      - CADDY_INGRESS_NETWORKS=web
    volumes:
      - $DATADIR/appdata/caddy:/data
    restart: unless-stopped
    labels:
      caddy.email: jamienibtong@gmail.com
      caddy.auto_https: "ignore_loaded_certs"
      logging: alloy
      logging_jobname: containerlogs

