services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.jamietong.com
    env_file: $DATADIR/mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    networks:
      web:
        ipv4_address: 10.10.0.3
    ports:
      - "25:25" # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143" # IMAP4 (explicit TLS => STARTTLS)
      - "465:465" # ESMTP (implicit TLS)
      - "587:587" # ESMTP (explicit TLS => STARTTLS)
      - "993:993" # IMAP4 (implicit TLS)
    volumes:
      - $DATADIR/appdata/dms/mail-data/:/var/mail/
      - $DATADIR/appdata/dms/mail-state/:/var/mail-state/
      - $DATADIR/appdata/dms/mail-logs/:/var/log/mail/
      - $DATADIR/appdata/dms/config/:/tmp/docker-mailserver/
      - $DATADIR/appdata/traefik3/acme/acme.json:/etc/letsencrypt/acme.json:ro # Certs File
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    # cap_add:
    #   - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s

  whoami:
    image: docker.io/traefik/whoami:latest
    labels:
      - "traefik.http.routers.whoami.rule=Host(`mail.jamietong.com`)"
