services:
  resolve-db:
    container_name: resolve-db
    image: postgres
    networks:
      - caddy-net 
    ports:
      - 5432:5432
    env_file: $DOCKERDIR/.env
    restart: always
    volumes:
      - $DATADIR/postgresql:/var/lib/postgresql/data 
