services:
  resolve-db:
    container_name: resolve-db
    image: postgres
    networks:
      - web
    ports:
      - 5432:5432
    env_file: $CONFIGDIR/.env
    restart: always
    volumes:
      - $MEDIADIR/postgresql:/var/lib/postgresql/data 
