services:
  syncyomi:
    container_name: syncyomi
    image: ghcr.io/syncyomi/syncyomi:latest
    volumes:
      - $DOCKERDIR/appdata/syncyomi/config:/config
    networks:
      web:
        ipv4_address: 10.10.0.4
    restart: unless-stopped
    labels:
      caddy_1: syncyomi.jamietong.com
      caddy_1.reverse_proxy: "{{upstreams 8282}}"

  syncyomi-two:
   container_name: syncyomi-two
   image: ghcr.io/syncyomi/syncyomi:latest
   volumes:
     - $DOCKERDIR/appdata/syncyomi-two/config:/config
   networks:
      web:
       ipv4_address: 10.10.0.5
   restart: unless-stopped
   labels:
     caddy_1: syncyomi-two.jamietong.com
     caddy_1.reverse_proxy: "{{upstreams 8282}}"
  
  
  
