networks:
  internal:
    name: internal
    external: true
  qbittorrent:
    name: qbittorrent
    external: true

services:
  qui:
    extends:
      file: ../common.yml
      service: app
    container_name: qui
    image: ghcr.io/autobrr/qui:latest
    networks:
      - internal
      - qbittorrent
    volumes:
      - $DATADIR/appdata/qui/config:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qui-rtr.entrypoints=internalsecure"
      - "traefik.http.routers.qui-rtr.rule=Host(`qui.${DOCKER_HOST_NAME}.i.$DOMAINNAME_1`) || Host(`qui.$DOMAINNAME_1`)"
      - "traefik.http.routers.qui-rtr.service=qui-svc"
      - "traefik.http.services.qui-svc.loadbalancer.server.port=7476"
      - "traefik.docker.network=internal"
      - "logging=alloy"
      - "logging_jobname=containerlogs"
